/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.pahema.ventanas;

import ar.com.pahema.hibernate.HibernateUtil;
import java.awt.Frame;
import org.hibernate.Session;

/**
 *
 * @author Dante
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    public static boolean abierta;
    private static Session sesionTango;
    private static Session sesionCRM;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        obtenerSesionHibernate();
        abierta = true;
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenu();
        mnuCargaHoras = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/pahema/imagenes/llave.png"))); // NOI18N
        jMenu1.setText("Control de llaves");
        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/pahema/imagenes/paquete.png"))); // NOI18N
        jMenu3.setText("Administrador");

        mnuClientes.setText("Clientes");
        mnuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuClientesMouseClicked(evt);
            }
        });

        mnuCargaHoras.setText("Carga de horas");
        mnuCargaHoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCargaHorasMouseClicked(evt);
            }
        });
        mnuCargaHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCargaHorasActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuCargaHoras);

        jMenu3.add(mnuClientes);

        jMenuItem1.setText("Paquetes");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/pahema/imagenes/salir.gif"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuClientesMouseClicked
        if (!ClientesAdministrador.abierta) {
            ClientesAdministrador c = new ClientesAdministrador();
            jDesktopPane1.add(c);
            c.setVisible(true);
        }
    }//GEN-LAST:event_mnuClientesMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        abierta = false;
    }//GEN-LAST:event_formWindowClosed

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        sesionCRM.close();
        sesionTango.close();
        System.out.println("sesiones cerradas!");
        this.dispose();
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("sesion cerrada!");
        //session.close();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void mnuCargaHorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCargaHorasMouseClicked
       if(!JD_CargaHorasClientes.abierta){
           JD_CargaHorasClientes j = new JD_CargaHorasClientes(new Frame(),true);
           j.setVisible(true);
       }
    }//GEN-LAST:event_mnuCargaHorasMouseClicked

    private void mnuCargaHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCargaHorasActionPerformed
       if(!JD_CargaHorasClientes.abierta){
           JD_CargaHorasClientes j = new JD_CargaHorasClientes(new Frame(),true);
           j.setVisible(true);
       }
    }//GEN-LAST:event_mnuCargaHorasActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        sesionCRM.close();
        sesionTango.close();
        System.out.println("sesiones cerradas!");
        this.dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PantallaPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuCargaHoras;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables

    private void obtenerSesionHibernate() {
        sesionCRM = HibernateUtil.currentSession();
        //HibernateUtil.addConfigFile("Tango.hibernate.cfg.xml", "Tango");
        //sesionTango = HibernateUtil.currentSession("Tango");
    }

}
